# Generated by Django 4.1.7 on 2023-03-31 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
