# Generated by Django 4.1.7 on 2023-03-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_like_created_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('sender', 'receiver')},
        ),
    ]
