# Generated by Django 4.1.7 on 2023-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_attachment_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('1', 'Image'), ('2', 'Video'), ('3', 'Audio'), ('4', 'File')], max_length=100),
        ),
    ]
